version: '3.1'
services:
  pm-database:
    container_name: pm-database
    image: mcr.microsoft.com/mssql/server
    ports:
      - 14331:1433
    volumes:
      - productmanager-db:/productmanager-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Asd@1234"
      MSSQL_PID: Express
  pm-api:
    container_name: pm-api
    build:
      context: . # This docker file should be in PM.Api folder by from there it can't restore class library project that's why it is here
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - 8080:80
  pm-web:
    container_name: pm-web
    build:
      context: ./PM.Web
    ports:
      - 80:80
volumes:
  productmanager-db: